on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello World Action Step
        id: hello
        uses: kristinhortsch/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'Ranger the Malamute'
      - name: Get the output time
        run: echo "The time was ${{steps.hello.outputs.time}}"
